### ISSUE TITLE
Cannot load your GroupSeq package

### ISSUE THREAD

**Issue by yukis4san** [rpahl/GroupSeq#1]
To whom it may concern,

I have been able to use GroupSeq a few months ago and now I cannot load your package.
install.packages("GroupSeq")
library(GroupSeq) <- here it stops.

Would you please help me figure out why it's not loading?

Thank you very much.

Sincerely,
Yuki

**Comment by rpahl** [comment]
Hi,

can you provide some more information? What is your operating system (Windows, Linux, Mac?) What R version are you running?
Best, Roman

**Comment by Neequaye** [comment]
I have a similar issue to that one above. I am able to install GroupSeq. However, I get the error message below when I try loading the package. I am using r studio. I tried in base r but got the same error message.

> library(GroupSeq)
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: package or namespace load failed for 'GroupSeq':
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so, 10): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/tcltk/libs/tcltk.so
  Reason: image not found
In addition: Warning message:
In system2("/usr/bin/otool", c("-L", shQuote(DSO)), stdout = TRUE) :
  running command ''/usr/bin/otool' -L '/Library/Frameworks/R.framework/Resources/library/tcltk/libs//tcltk.so'' had status 1

**Comment by Neequaye** [comment]
Ps. I am using a mackbook pro

**Comment by rpahl** [comment]
Hi, 
it seems that your system is missing the Tcl/Tk library, which is required for the graphical user interface. Please try the fix described in the link below:
[fix-r-tcltk-dependency-problem-on-mac](https://planspace.org/2013/01/17/fix-r-tcltk-dependency-problem-on-mac/)

Best regards, Roman

**Comment by Neequaye** [comment]
Hi, 
The recommended solution worked perfectly. Thanks for taking the time out to help me with this. I appreciate it.

Best,
David

**Comment by rpahl** [comment]
You're welcome :)
