### ISSUE TITLE
Menu to Save to File is mostly off screen

### ISSUE THREAD

**Issue by TimHesterberg** [rpahl/GroupSeq#16]
I'm computing Bounds.
Show Graph works
Save to File - gives a popup that is mostly off screen.
The top is off screen, so I can't move it.

I have a laptop on the left, and large monitor arranged vertically on the right, that extends both below and above the laptop.
This popup appears in the top right of the laptop, and parts of the window
are above and to the right of the laptop screen.
The part to the right should appear in the large monitor, but doesn't.
<img width="1787" alt="Screenshot 2024-01-31 at 15 48 54" src="https://github.com/rpahl/GroupSeq/assets/32824892/33a970e2-41b4-4c64-97ff-c679d990e270">

**Comment by rpahl** [comment]
I have no idea how to fix this, to be honest, plus I unfortunately don't have the setup to reproduce the error. It might be controllable via the underlying tcl/tk API, which however goes beyond my scope of tcl knowledge.
