### ISSUE TITLE
GUI Not Loading

### ISSUE THREAD

**Issue by zbaker9113** [rpahl/GroupSeq#2]
Hello,

In RStudio 3.5.2 on Windows. Package is installing and loading just fine, but I'm having trouble getting the GUI to open.

Some code:
> library(GroupSeq)
package �GroupSeq� was built under R version 3.5.3
> groupseq()
<Tcl>  

Thanks for your help!

**Comment by rpahl** [comment]
Hi,
I could not replicate your error. The GUI should open automatically when the package is loaded via
`library(GroupSeq)`
I noticed, however, that under RStudio it does so silently, that is, the window is not brought to the front. So please check, if you can spot something in your task bar - the symbol should look like a feather:
![image](https://user-images.githubusercontent.com/11405819/61580872-0fd92f80-ab17-11e9-9f6d-f533788e80b6.png)
If that does not work, you could next try to start it from the R console, that is, without referring to RStudio.

**Comment by zbaker9113** [comment]
What a silly mistake on my part, I see it in my taskbar. Thanks very much for your help!

**Comment by rpahl** [comment]
No problem - glad I could help and have fun with the GUI :-)
