### ISSUE TITLE
Cannot open GUI on Mac

### ISSUE THREAD

**Issue by mkilb** [rpahl/GroupSeq#3]
Hey,

I have problems opening the guy via library(GroupSeq). The following error message occurs:

> Fehler: package or namespace load failed for ‘GroupSeq’:
>  .onAttach in attachNamespace() für 'GroupSeq' fehlgeschlagen, Details:
>   Aufruf: structure(.External(.C_dotTclObjv, objv), class = "tclObj")
>   Fehler: [tcl] invalid command name "toplevel".

I am currently using R version 3.6.1 with RStudio Version 1.2.1335 on Macos Mojave Version 10.14.5. I would be really happy, if you would have any suggestions to fix the problem!

Best wishes,
Michael

**Comment by rpahl** [comment]
Hi Michael,

the error happens with the tcltk library, which is running the graphical user interface. I did a brief internet search and apparently some people had similar issues in context with RStudio, so my first suggestions would to:

1. Try updating to the newest version of RStudio
2. If this does not help, try starting R using one of the R binaries (i.e. without RStudio) and try loading the library from the R console.
3. If still not working, try re-installing the tcltk library via install.packages("tcltk")

Let me know, if one of this works.

Best,
Roman

**Comment by mkilb** [comment]
Hi Roman,

thanks for your answer! R and RStudio are already the newest versions. When I am trying to load the package out of base R i get another error message:

> Fehler: package or namespace load failed for ‘GroupSeq’:
>  .onAttach in attachNamespace() für 'GroupSeq' fehlgeschlagen, Details:
>   Aufruf: structure(.External(.C_dotTclObjv, objv), class = "tclObj")
>   Fehler: [tcl] invalid command name "toplevel".
> Zusätzlich: Warnmeldung:
> In fun(libname, pkgname) : couldn't connect to display ":0"

The installation/ update of tcltk is also not working:

> Warning in install.packages :
>   package ‘tcltk’ is not available (for R version 3.6.1)
> Warning in install.packages :
>   package ‘tcltk’ is a base package, and should not be updated

Best wishes,
Michael

**Comment by rpahl** [comment]
Hi,

I think I have located the issue. I went to https://cran.r-project.org/bin/macosx/ and there it says in the notes for the latest release:

> Note: the use of X11 (including tcltk) requires [XQuartz](http://xquartz.macosforge.org/) to be installed since it is no longer part of OS X. Always re-install XQuartz when upgrading your macOS to a new major version.

So just install XQuartz - this should fix your problem :)

**Comment by mkilb** [comment]
Hi Roman,

I already installed it earlier, but thank you again for your hint! I had to start XQuartz manually before loading the package - so now it works! :)

Thank you very much for your help!

Best,
Michael
